GET http://localhost:3000/api/wine
###
GET http://localhost:3000/api/wine/2
###
POST http://localhost:3000/api/wine
Content-Type: application/json

{
  "name":"Amor",
  "elaborationArea":"Roma",
  "photo":"www.fffff.es",
  "Origin_id":1,
  "WineCellar_id":1,
"Type_id":4,
"Grape_id":1 
}

###

PUT http://localhost:3000/api/wine/2
Content-Type: application/json

{
  "name":"Amor",
  "elaborationArea":"Florencia",
  "photo":"www.fffff.es",
  "Origin_id":1,
  "WineCellar_id":1
}

###
GET http://localhost:3000/api/wineHasUser/user/1

###
GET http://localhost:3000/api/wineHasUser/1

###
POST http://localhost:3000/api/wineHasUser
Content-Type: application/json

{
  "Wine_id":2,
  "User_id":1,
  "favorite":false,
  "taste":true
}

###
PUT http://localhost:3000/api/wineHasUser/favorite/2
Content-Type: application/json

{
  "favorite":true
}

###
PUT http://localhost:3000/api/wineHasUser/taste/2
Content-Type: application/json

{
  "taste":true
}

###
DELETE http://localhost:3000/api/wineHasUser/5

###

GET http://localhost:3000/api/origin
###
GET http://localhost:3000/api/origin/1
###
POST http://localhost:3000/api/origin
Content-Type: application/json

{
  "type": "DOP",
  "name":"Rivera del Duero"
}

###

PUT http://localhost:3000/api/origin/1
Content-Type: application/json

{
  "type": "DOP",
  "name":"Rosa"
}

###


GET http://localhost:3000/api/wineCellar
###
GET http://localhost:3000/api/wineCellar/1
###
POST http://localhost:3000/api/wineCellar
Content-Type: application/json

{
  "name":"Romero Gutierrez",
  "Origin_id": 2
}

###

PUT http://localhost:3000/api/wineCellar/2
Content-Type: application/json

{
  "name":"Roca",
  "Origin_id": 2
}

####
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "email": "bea@gmail.com",
  "name":"Bea",
  "password": "12345"
}

###

GET http://localhost:3000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE2NjAyMzE0NzB9.8eoo7Et8ztCFRJi1cn-1VG2IHItE08h_BicIV_Aps8c

###
GET http://localhost:3000/api/users/1
###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "rosa@gmail.com",
  "password": "12345"
}

###
PUT http://localhost:3000/api/users/status/2
Content-Type: application/json

{
  "isActive": true
}
###

PUT http://localhost:3000/api/users/8
Content-Type: application/json

{
  "id": 8,
  "email": "rosa@gmail.com",
  "name":"Rosas",
  "password": "12345"
}

###
POST http://localhost:3000/api/users/recoverPassword
Content-Type: application/json

{
  "email": "rosa@gmail.com"
}
###
POST http://localhost:3000/api/users/password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJpYXQiOjE2NTk5NTg3NzV9.95EcIx5Zs7MWpgM4vHY_PcnEfbgjUQpEojdFZ6lyrcI
Content-Type: application/json

{
  "password": "1235"
}

###

GET http://localhost:3000/api/type
###
GET http://localhost:3000/api/type/1
###
POST http://localhost:3000/api/type
Content-Type: application/json

{
  "name":"Fino"
}

###

PUT http://localhost:3000/api/type/1
Content-Type: application/json

{
  "name":"Rosa"
}

###

GET http://localhost:3000/api/grape
###
GET http://localhost:3000/api/grape/1
###
POST http://localhost:3000/api/grape
Content-Type: application/json

{
  "name":"Tempranillo"
}

###

PUT http://localhost:3000/api/grape/1
Content-Type: application/json

{
  "name":"Moscatel"
}